apiVersion: v1
kind: Secret

metadata:
  name: auth-service-secret

type: Opaque

stringData:
  MONGODB_URI: "mongodb+srv://gxcmqhxshaw4oh:Omnicart1@docdb-cluster-20260819-1634.mongocluster.cosmos.azure.com/?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"
  JWT_ACCESS_SECRET: "replace-with-a-strong-access-secret"
  JWT_ACCESS_EXPIRATION: "15m"
  JWT_REFRESH_SECRET: "replace-with-a-strong-refresh-secret"
  JWT_REFRESH_EXPIRATION: "7d"